INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 401);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 2, 402);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 2, 403);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 404);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 405);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 406);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 407);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 408);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 409);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 410);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 411);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 502);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 2, 503);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 2, 504);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 506);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 507);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 508);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 509);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 512);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 513);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 514);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 523);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 532);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('GRAND', 1, 537);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 510);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 511);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 515);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 516);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 517);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 518);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 519);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 520);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 521);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 522);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 524);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 525);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 526);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 527);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 528);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 529);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 530);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 531);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 533);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 1, 534);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 535);
INSERT INTO location (piano_category, piano_count, room_no) VALUES ('UPRIGHT', 2, 536);

# INSERT INTO event (lessor_name, start_date_time, end_date_time, location_id) VALUES ('황태원', '2018-02-28 12:34:00', '2018-02-28 13:04:00', 1);
# INSERT INTO event (lessor_name, start_date_time, end_date_time, location_id) VALUES ('윤혁주', '2018-02-28 14:56:00', '2018-02-28 15:26:00', 2);
# INSERT INTO event (lessor_name, start_date_time, end_date_time, location_id) VALUES ('신동준', '2020-02-29 14:56:00', '2020-02-29 15:26:00', 2);
INSERT INTO event (lessor_name, start_date_time, end_date_time, location_id) VALUES ('신동준', '2019-03-13 14:00:00', '2019-03-13 15:00:00', 2);

INSERT INTO EVENT_TIME(time) VALUES('2019-03-11 15:26:00');